### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by SNaveenMathew** [miotto/treetagger-python#9]
I ran the given example code and got the following error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/treetagger.py", line 141, in tag
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error```

**Comment by miotto** [comment]
Please use the latest version of TreeTagger-python for Python 3.
